### ISSUE TITLE
Featurizer throwing error

### ISSUE THREAD

**Issue by Mark-a-Lis** [cuzzo87/CNN_DockBench#12]
I'm trying to run the example in the readme, but am getting the same error and I'm not sure what to do about it. 

Here's the trace

home~/CNN_DockBench/cnndockbench$ python prod.py -pdb example/3ptb_protein.pdb -smi example/nicotine.smi -x -1.759 -y 14.461 -z 16.916 -output example/ls
2021-02-08 21:23:59,189 - DockBenchPred - INFO - Performing sanity checks...
2021-02-08 21:23:59,189 - DockBenchPred - INFO - Processing ligands...
2021-02-08 21:23:59,190 - DockBenchPred - INFO - Preparing the protein...
2021-02-08 21:23:59,509 - propka - INFO - No pdbfile provided
2021-02-08 21:24:00,749 - numexpr.utils - INFO - NumExpr defaulting to 2 threads.
2021-02-08 21:24:06,029 - moleculekit.tools.atomtyper - INFO - Checking validity of Molecule before atomtyping. If it gives incorrect results or to improve performance disable it with validitychecks=False. Most of these checks can be passed by using the moleculekit.atomtyper.prepareProteinForAtomtyping function. But make sure you understand what you are doing.
==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is /tmp/tmpcizlh888.pdb)
2021-02-08 21:24:07,103 - DockBenchPred - INFO - Now predicting...
Traceback (most recent call last):
  File "prod.py", line 114, in <module>
    rmsd_min, rmsd_ave, n_rmsd = dn.run_net()
  File "prod.py", line 73, in run_net
    featurizer = FeaturizerProd(self.coords, self.grid_centers, self.channels, self.mols)
  File "/home/CNN_DockBench/cnndockbench/utils_prod.py", line 26, in __init__
    self.desc_cols = np.load(os.path.join(os.path.dirname(__file__), 'data', 'desc_cols.npy'))
  File "/opt/conda/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/CNN_DockBench/cnndockbench/data/desc_cols.npy'

Any ideas? 
Thanks!

**Comment by josejimenezluna** [comment]
Hi @Mark-a-Lis,
did you download the auxiliary data that was mentioned in the README file? 

Thanks for trying our model! :)
